<?php
//Arquivo para deslogar
    session_start(); // inicia a sessão...

    unset($_SESSION['id_usuario']); //destroi a sessão se não possui um id_usuario (não estiver logado)...
    header("location: ../../resources/View/Pages/login.php"); //se o usuario nao possuir um id_usuario, manda ele devolta para a página login.php...

?>